language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "nightly"

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH


install:
  - conda create --yes -n test python=$TRAVIS_PYTHON_VERSION
  - source activate test
  - conda install --channel conda-forge geopandas
  - conda install rasterio
  - conda install pandas
  - conda install numpy
  - conda install scikit-learn
  - "pip install pytest"
script: python -m unittest