dist: xenial

language: python

cache: pip

python:
    - "3.6"
    - "3.7"
    - "3.8"
    - "nightly"

before_install:
    - sudo apt-get update
    - sudo apt-get install gdal-bin
    - sudo apt-get install libgdal-dev

install:
    - pip install ogr
    - pip install gdal
    - pip install fiona
    - pip install rasterio
    - pip install sklearn
    - poetry install
script:
    - bash scripts/test.sh

