dist: xenial

language: python

cache: pip

python:
    - "3.6"
    - "3.7"
    - "3.8"
    - "nightly"

install:
    - pip install wheel
    - pip install pipwin
    - pipwin install numpy
    - pipwin install pandas
    - pipwin install shapely
    - pipwin install gdal
    - pipwin install fiona
    - pipwin install pyproj
    - pipwin install six
    - pipwin install rtree
    - pipwin install geopandas
    - pip install poetry

script:
    - bash scripts/test.sh

